# Generated by Django 5.2.1 on 2025-05-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_countryvisit'),
    ]

    operations = [
    ]
