# Generated by Django 5.2 on 2025-05-15 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_countryvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('visit_time', models.TimeField(default=django.utils.timezone.now)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['visit_date'], name='core_visit_visit_d_26d9ec_idx')],
            },
        ),
    ]
