# Generated by Django 5.2 on 2025-05-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('winter', 'Зима'), ('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень')], max_length=10)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_visits', to='core.country')),
            ],
            options={
                'unique_together': {('country', 'season')},
            },
        ),
    ]
