# Generated by Django 5.2 on 2025-05-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_travelticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='tickets/pdfs/')),
                ('ticket_image', models.ImageField(blank=True, null=True, upload_to='tickets/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='travelticket',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='tickets/pdfs/'),
        ),
    ]
