# Generated by Django 5.2 on 2025-05-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seasonalvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='tourists_autumn',
            field=models.PositiveIntegerField(default=0, verbose_name='Туристы (осень)'),
        ),
        migrations.AddField(
            model_name='country',
            name='tourists_spring',
            field=models.PositiveIntegerField(default=0, verbose_name='Туристы (весна)'),
        ),
        migrations.AddField(
            model_name='country',
            name='tourists_summer',
            field=models.PositiveIntegerField(default=0, verbose_name='Туристы (лето)'),
        ),
        migrations.AddField(
            model_name='country',
            name='tourists_winter',
            field=models.PositiveIntegerField(default=0, verbose_name='Туристы (зима)'),
        ),
    ]
