# Generated by Django 5.2 on 2025-05-27

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_country_tourists_autumn_country_tourists_spring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryvisit',
            name='season',
            field=models.CharField(
                choices=[
                    ('winter', 'Winter'),
                    ('spring', 'Spring'),
                    ('summer', 'Summer'),
                    ('autumn', 'Autumn')
                ],
                default='summer',
                max_length=20,
            ),
        ),
    ]
