# Generated by Django 5.2 on 2025-05-27

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_season_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryvisit',
            options={'ordering': ['season']},
        ),
        migrations.AlterUniqueTogether(
            name='countryvisit',
            unique_together={('country', 'season')},
        ),
        migrations.RemoveField(
            model_name='countryvisit',
            name='month',
        ),
    ]
